import 'package:flutter/material.dart';

import '../config/theme.dart';
import '../main.dart';
import '../models/models.dart';
import '../services/kheja_api.dart';
import '../widgets/states.dart';
import 'auth_screen.dart';
import 'property_detail_screen.dart';

/// The in-app notification centre.
///
/// Everything here is generated by database triggers: a home you liked coming
/// back on the market, a booking, a check-in, a move-out, a new inquiry. There
/// is no push infrastructure — these are read when the app is open.
class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> {
  late Future<List<KhejaNotification>> _future;

  @override
  void initState() {
    super.initState();
    _future = khejaApi.fetchNotifications();
  }

  Future<void> _refresh() async {
    final future = khejaApi.fetchNotifications();
    setState(() => _future = future);
    await future;
  }

  Future<void> _markAllRead() async {
    await khejaApi.markAllNotificationsRead();
    if (!mounted) return;
    showKhejaSnack(context, 'All caught up.');
    await _refresh();
  }

  Future<void> _open(KhejaNotification n) async {
    if (!n.isRead) {
      await khejaApi.markNotificationRead(n.id);
      if (mounted) _refresh();
    }
    final propertyId = n.propertyId;
    if (propertyId == null || !mounted) return;

    // Notifications carry a property id, not a slug, so resolve it first.
    try {
      final slug = await khejaApi.fetchPropertySlug(propertyId);
      if (slug == null || !mounted) return;
      await Navigator.of(context).push(
        MaterialPageRoute(builder: (_) => PropertyDetailScreen(slug: slug)),
      );
    } catch (_) {
      // A deleted listing is not worth an error message here.
    }
  }

  @override
  Widget build(BuildContext context) {
    if (!khejaApi.isSignedIn) {
      return Scaffold(
        appBar: AppBar(title: const Text('Notifications')),
        body: KhejaEmptyState(
          icon: Icons.notifications_none_rounded,
          title: 'Sign in for alerts',
          message: 'We will tell you the moment a home you liked becomes vacant '
              'again, and keep you posted on your bookings.',
          actionLabel: 'Sign in',
          onAction: () async {
            await Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => const AuthScreen()));
            if (mounted) _refresh();
          },
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Notifications'),
        actions: [
          TextButton(onPressed: _markAllRead, child: const Text('Mark all read')),
          const SizedBox(width: 8),
        ],
      ),
      body: RefreshIndicator(
        color: KhejaColors.blue,
        onRefresh: _refresh,
        child: FutureBuilder<List<KhejaNotification>>(
          future: _future,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(
                child: CircularProgressIndicator(color: KhejaColors.blue),
              );
            }
            if (snapshot.hasError) {
              return KhejaErrorState(
                message: describeError(snapshot.error!),
                onRetry: _refresh,
              );
            }

            final items = snapshot.data ?? const [];
            if (items.isEmpty) {
              return ListView(
                physics: const AlwaysScrollableScrollPhysics(),
                children: const [
                  SizedBox(height: 60),
                  KhejaEmptyState(
                    icon: Icons.notifications_none_rounded,
                    title: 'Nothing yet',
                    message: 'Like a few homes and we will tell you when one of '
                        'them frees up.',
                  ),
                ],
              );
            }

            return ListView.separated(
              padding: const EdgeInsets.fromLTRB(20, 12, 20, 32),
              physics: const AlwaysScrollableScrollPhysics(),
              itemCount: items.length,
              separatorBuilder: (_, __) => const SizedBox(height: 12),
              itemBuilder: (context, i) =>
                  _NotificationTile(item: items[i], onTap: () => _open(items[i])),
            );
          },
        ),
      ),
    );
  }
}

class _NotificationTile extends StatelessWidget {
  const _NotificationTile({required this.item, required this.onTap});

  final KhejaNotification item;
  final VoidCallback onTap;

  static ({IconData icon, Color color}) _style(String type) => switch (type) {
        'vacancy' => (icon: Icons.celebration_rounded, color: KhejaColors.emerald),
        'inquiry' => (icon: Icons.mark_email_unread_rounded, color: KhejaColors.blue),
        'booking' => (icon: Icons.event_available_rounded, color: KhejaColors.purple),
        'check_in' => (icon: Icons.login_rounded, color: KhejaColors.emerald),
        'move_out' => (icon: Icons.logout_rounded, color: KhejaColors.amber),
        'listing_status' => (icon: Icons.home_work_rounded, color: KhejaColors.zinc500),
        _ => (icon: Icons.info_rounded, color: KhejaColors.blue),
      };

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final style = _style(item.type);

    return Material(
      color: theme.colorScheme.surface,
      borderRadius: BorderRadius.circular(KhejaRadius.xl),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(KhejaRadius.xl),
        child: Container(
          padding: const EdgeInsets.all(18),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(KhejaRadius.xl),
            border: Border.all(
              color: item.isRead
                  ? theme.colorScheme.outline
                  : KhejaColors.blue.withValues(alpha: 0.45),
              width: item.isRead ? 1 : 1.4,
            ),
          ),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 42,
                height: 42,
                decoration: BoxDecoration(
                  color: style.color.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(KhejaRadius.md),
                ),
                child: Icon(style.icon, size: 20, color: style.color),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(item.title, style: theme.textTheme.titleMedium),
                        ),
                        if (!item.isRead)
                          Container(
                            width: 8,
                            height: 8,
                            decoration: const BoxDecoration(
                              color: KhejaColors.blue,
                              shape: BoxShape.circle,
                            ),
                          ),
                      ],
                    ),
                    if (item.body != null) ...[
                      const SizedBox(height: 4),
                      Text(
                        item.body!,
                        style: const TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.w500,
                          color: KhejaColors.zinc500,
                          height: 1.45,
                        ),
                      ),
                    ],
                    const SizedBox(height: 8),
                    Text(
                      formatRelativeDate(item.createdAt).toUpperCase(),
                      style: kEyebrowStyle.copyWith(color: KhejaColors.zinc400),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
